# Site settings
title: "Dina Yerlan"
email: s.dina.e@gmail.com
description: "Github portal for personal projects."
url: https://di-y.github.io
shorturl: di-y.github.io
title_description: "KPCB Product Fellow Application"
title_image: "ava.jpg"
google_analytics: "UA-66023783-1"
disqus_account: di-ygithubio
github_repository: https://github.com/di-y/di-y.github.io
post_limit: 100

# Social usernames/URLs
twitter_username: di-y
github_username:  di-y
linkedin_link: https://in.linkedin.com/in/dinayerlan

# Footer
footer_left: "Made by <a href=\""https://github.com/di-y\">Dina Yerlan</a>"
footer_right: " "



# Build settings
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
exclude: [vendor]
