
title: "Dina Yerlan"
email: s.dina.e@gmail.com
description: "Github portal for personal projects."
url: https://di-y.github.io
shorturl: di-y.github.io
title_description: "This is the virtual Dina. I'm passionate about learning new things, building great products and startups!"
title_image: "ava.jpg"
google_analytics: "UA-66023783-1"
disqus_account: di-ygithubio
github_repository: https://github.com/di-y/di-y.github.io
post_limit: 100

# Social usernames/URLs
twitter_username: di-y
github_username:  di-y
linkedin_link: https://in.linkedin.com/in/dinayerlan

# Footer
footer_right: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://www.linkedin.com/in/dinayerlan\">Dina Yerlan</a>"
footer_left: "&lt;/&gt; on <a href=\"https://github.com/di-y\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"


# Build settings
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
exclude: [vendor]
