
title: "Dina Yerlan"
email: s.dina.e@gmail.com
description: "Github portal for personal projects."
url: https://di-y.github.io/
shorturl: https://di-y.github.io/
title_description: "ep following and subscribe to the RSS feeds to find useful stories and beautiful visualisations."
title_image: "https://static-videos.pexels.com/images/video-pictures/1/preview-4.jpg"
google_analytics: "UA-66023783-1"
disqus_account: di-ygithubio
github_repository: https://github.com/di-y/di-y.github.io
post_limit: 100

# Social usernames/URLs
twitter_username: di-y
github_username:  di-y
linkedin_link: https://in.linkedin.com/in/dinayerlan

# Footer

# Build settings
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
exclude: [vendor]
